Repository Pool-Of-Tears/GreenStash, pull requests merged in 2024-05, with the labels that each got.

#111 Add Haptic feedback and improve tip UI
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/starry/greenstash/MainActivity.kt
  app/src/main/java/com/starry/greenstash/ui/common/DateTimeCard.kt
  app/src/main/java/com/starry/greenstash/ui/common/TipCard.kt
  app/src/main/java/com/starry/greenstash/ui/screens/backups/composables/BackupScreen.kt
  app/src/main/java/com/starry/greenstash/ui/screens/dwscreen/composables/DWScreen.kt
  app/src/main/java/com/starry/greenstash/ui/screens/home/composables/GoalLazyItem.kt
  app/src/main/java/com/starry/greenstash/ui/screens/home/composables/HomeAppBars.kt
  app/src/main/java/com/starry/greenstash/ui/screens/home/composables/HomeDialogs.kt
  app/src/main/java/com/starry/greenstash/ui/screens/home/composables/HomeDrawer.kt
  app/src/main/java/com/starry/greenstash/ui/screens/home/composables/HomeScreen.kt
  app/src/main/java/com/starry/greenstash/ui/screens/info/composables/GoalInfoScreen.kt
  app/src/main/java/com/starry/greenstash/ui/screens/info/composables/TransactionItems.kt
  app/src/main/java/com/starry/greenstash/ui/screens/input/composables/InputScreen.kt
  app/src/main/java/com/starry/greenstash/ui/screens/settings/composables/GoalCardStyle.kt
  app/src/main/java/com/starry/greenstash/ui/screens/settings/composables/SettingsItem.kt
  app/src/main/java/com/starry/greenstash/ui/screens/settings/composables/SettingsScreen.kt
  app/src/main/java/com/starry/greenstash/utils/Extensions.kt
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#112 Add black amoled theme
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/starry/greenstash/ui/screens/input/composables/IconPickerDialog.kt
  app/src/main/java/com/starry/greenstash/ui/screens/settings/SettingsViewModel.kt
  app/src/main/java/com/starry/greenstash/ui/screens/settings/composables/SettingsScreen.kt
  app/src/main/java/com/starry/greenstash/ui/theme/Color.kt
  app/src/main/java/com/starry/greenstash/ui/theme/Theme.kt
  app/src/main/java/com/starry/greenstash/utils/PreferenceUtil.kt
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#118 Improve navigation drawer UI
  .idea/deploymentTargetSelector.xml
  app/build.gradle
  app/src/main/java/com/starry/greenstash/MainActivity.kt
  app/src/main/java/com/starry/greenstash/ui/screens/home/composables/HomeAppBars.kt
  app/src/main/java/com/starry/greenstash/ui/screens/home/composables/HomeDrawer.kt
  app/src/main/java/com/starry/greenstash/ui/screens/home/composables/HomeScreen.kt
  app/src/main/java/com/starry/greenstash/ui/screens/info/composables/EditTransactionSheet.kt
  app/src/main/java/com/starry/greenstash/ui/screens/input/composables/InputScreen.kt
  app/src/main/java/com/starry/greenstash/ui/screens/settings/composables/AboutScreen.kt
  app/src/main/java/com/starry/greenstash/ui/screens/settings/composables/GoalCardStyle.kt
  app/src/main/java/com/starry/greenstash/ui/screens/settings/composables/SettingsScreen.kt
  app/src/main/java/com/starry/greenstash/ui/theme/Theme.kt
  app/src/main/java/com/starry/greenstash/utils/Utils.kt
  app/src/main/java/com/starry/greenstash/widget/configuration/WidgetConfigActivity.kt
  app/src/main/res/drawable/ic_nav_backups.xml
  app/src/main/res/drawable/ic_nav_privacy.xml
  app/src/main/res/drawable/ic_nav_rating.xml
  app/src/main/res/drawable/ic_nav_share.xml
  app/src/main/res/drawable/ic_settings_about.xml
  app/src/main/res/drawable/ic_settings_app_lock.xml
  app/src/main/res/drawable/ic_settings_material_you.xml
  app/src/main/res/drawable/ic_settings_osl.xml
  app/src/main/res/drawable/ic_settings_sort_order.xml
  app/src/main/res/drawable/ic_settings_theme.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#119 Add ability to archive completed goals
  .idea/deploymentTargetSelector.xml
  app/schemas/com.starry.greenstash.database.core.AppDatabase/6.json
  app/schemas/com.starry.greenstash.database.core.AppDatabase/7.json
  app/src/main/java/com/starry/greenstash/database/core/AppDatabase.kt
  app/src/main/java/com/starry/greenstash/database/goal/Goal.kt
  app/src/main/java/com/starry/greenstash/database/goal/GoalDao.kt
  app/src/main/java/com/starry/greenstash/database/transaction/TransactionDao.kt
  app/src/main/java/com/starry/greenstash/database/widget/WidgetDao.kt
  app/src/main/java/com/starry/greenstash/ui/common/ExpandableCard.kt
  app/src/main/java/com/starry/greenstash/ui/navigation/DrawerScreens.kt
  app/src/main/java/com/starry/greenstash/ui/navigation/NavGraph.kt
  app/src/main/java/com/starry/greenstash/ui/screens/archive/ArchiveViewModel.kt
  app/src/main/java/com/starry/greenstash/ui/screens/archive/composables/ArchiveScreen.kt
  app/src/main/java/com/starry/greenstash/ui/screens/backups/composables/BackupScreen.kt
  app/src/main/java/com/starry/greenstash/ui/screens/home/HomeViewModel.kt
  app/src/main/java/com/starry/greenstash/ui/screens/home/composables/GoalItems.kt
  app/src/main/java/com/starry/greenstash/ui/screens/home/composables/GoalLazyItem.kt
  app/src/main/java/com/starry/greenstash/ui/screens/home/composables/HomeDialogs.kt
  app/src/main/java/com/starry/greenstash/ui/screens/home/composables/HomeDrawer.kt
  app/src/main/java/com/starry/greenstash/ui/screens/home/composables/HomeScreen.kt
  app/src/main/java/com/starry/greenstash/ui/screens/info/composables/GoalInfoScreen.kt
  app/src/main/java/com/starry/greenstash/ui/screens/input/composables/InputScreen.kt
  app/src/main/java/com/starry/greenstash/ui/screens/other/CongratsScreen.kt
  app/src/main/java/com/starry/greenstash/ui/screens/settings/composables/AboutScreen.kt
  app/src/main/java/com/starry/greenstash/ui/screens/settings/composables/GoalCardStyle.kt
  app/src/main/java/com/starry/greenstash/ui/screens/settings/composables/OSLScreen.kt
  app/src/main/java/com/starry/greenstash/ui/screens/settings/composables/SettingsScreen.kt
  app/src/main/java/com/starry/greenstash/widget/configuration/WidgetConfigActivity.kt
  app/src/main/res/drawable/ic_compact_goal_archve.xml
  app/src/main/res/drawable/ic_compact_goal_deposit.xml
  app/src/main/res/drawable/ic_compact_goal_withdraw.xml
  app/src/main/res/drawable/ic_nav_archive.xml
  app/src/main/res/drawable/ic_nav_backups.xml
  app/src/main/res/drawable/ic_nav_privacy.xml
  app/src/main/res/drawable/ic_transaction_deposit.xml
  app/src/main/res/drawable/ic_transaction_withdraw.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#122 feat: Add ability to switch app locale on Android 13 & above
  app/build.gradle
  app/src/main/java/com/starry/greenstash/ui/screens/home/composables/GoalItems.kt
  app/src/main/java/com/starry/greenstash/ui/screens/info/composables/GoalInfoScreen.kt
  app/src/main/java/com/starry/greenstash/ui/screens/settings/composables/SettingsScreen.kt
  app/src/main/res/resources.properties
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#125 refactor: Add docstrings and remove redundant annotations
  app/src/main/java/com/starry/greenstash/reminder/ReminderManager.kt
  app/src/main/java/com/starry/greenstash/reminder/ReminderNotificationSender.kt
  app/src/main/java/com/starry/greenstash/reminder/receivers/BootReceiver.kt
  app/src/main/java/com/starry/greenstash/reminder/receivers/DateTimeChangeReceiver.kt
  app/src/main/java/com/starry/greenstash/ui/screens/archive/ArchiveViewModel.kt
  app/src/main/java/com/starry/greenstash/utils/GoalTextUtils.kt
  app/src/main/java/com/starry/greenstash/utils/ImageUtils.kt
  app/src/main/java/com/starry/greenstash/utils/PreferenceUtil.kt
  app/src/main/res/font/opensans_variablefont_wdth_wght.ttf
Labels: enhancement

#120 Added improvements to Github workflow
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE/translations_template.md
  CONTRIBUTING.md
  README.md
Labels: enhancement

#134 fix: Fix backup files not getting saved in some cases
  app/src/main/java/com/starry/greenstash/backup/BackupManager.kt
  app/src/main/res/xml/provider_paths.xml
Labels: bug

#135 fix: Add missing nested scroll connection in goal card settings
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/deploymentTargetSelector.xml
  .idea/misc.xml
  app/src/main/java/com/starry/greenstash/ui/screens/home/composables/GoalItems.kt
  app/src/main/java/com/starry/greenstash/ui/screens/settings/composables/GoalCardStyle.kt
Labels: enhancement

#136 fix: Fix build warnings due to multiple non-positional string substitutions
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: fix

#137 style: Improve consistency of some icons
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/starry/greenstash/ui/screens/home/composables/GoalItems.kt
  app/src/main/java/com/starry/greenstash/ui/screens/home/composables/HomeAppBars.kt
  app/src/main/res/drawable/ic_menu_filter.xml
Labels: enhancement

#138 feat: Improve widget design & responsiveness
  .idea/deploymentTargetSelector.xml
  .idea/misc.xml
  app/src/main/java/com/starry/greenstash/utils/NumberUtils.kt
  app/src/main/java/com/starry/greenstash/utils/Utils.kt
  app/src/main/java/com/starry/greenstash/widget/GoalWidget.kt
  app/src/main/res/drawable/ic_widget_refresh.xml
  app/src/main/res/drawable/widget_preview.png
  app/src/main/res/layout/goal_widget.xml
  build.gradle
Labels: enhancement

#139 feat: Add launcher shortcuts for quick access to some functionalities
  .idea/deploymentTargetSelector.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starry/greenstash/MainActivity.kt
  app/src/main/java/com/starry/greenstash/MainViewModel.kt
  app/src/main/java/com/starry/greenstash/ui/screens/settings/composables/AboutScreen.kt
  app/src/main/java/com/starry/greenstash/utils/Utils.kt
  app/src/main/java/com/starry/greenstash/widget/GoalWidget.kt
  app/src/main/res/drawable/ic_shortcut_new_goal.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, feature

#140 Bump version
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/370.txt
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/android/en-US/title.txt
Labels: new-releease

#141 feat: Update to Kotlin 2.0 & enable `enableStrongSkippingMode` for compose compiler
  .gitignore
  .idea/kotlinc.xml
  app/build.gradle
  build.gradle
Labels: enhancement
